POST https://iptcyn9bvi.execute-api.eu-west-1.amazonaws.com/prod
Content-Type: application/json

{
  "language_code": "en_UK",
  "text": "river winds no flower thou kissings"
}

###

POST https://iptcyn9bvi.execute-api.eu-west-1.amazonaws.com/prod
Content-Type: application/json

{
  "language_code": "de",
  "text": "guten"
}

###

POST http://localhost:9000/2015-03-31/functions/function/invocations
Content-Type: application/json

{
  "body": "{\"language_code\": \"en_UK\", \"text\": \"Apricot Apple Avocado\"}"
}

###
